import { WithId } from 'mongodb';
import * as z from 'zod';

import { ECountryCode, EIndustry, EStateCode } from '.';

export const Info = z.object({
  documentId: z.string().nonempty(),
  text: z.string().nonempty(),
  vectors: z.array(z.number()),
  countryCode: z.nativeEnum(ECountryCode),
  stateCode: z.nativeEnum(EStateCode),
  industry: z.nativeEnum(EIndustry),
});

export type Info = z.infer<typeof Info>;
export type InfoWithId = WithId<Info>;

export const InfoRequest = z.object({
  documentId: z.string().nonempty(),
  text: z.string().nonempty(),
  countryCode: z.nativeEnum(ECountryCode),
  stateCode: z.nativeEnum(EStateCode),
  industry: z.nativeEnum(EIndustry),
  // Vectors are not required because they are generated by the backend
});

export type InfoRequest = z.infer<typeof InfoRequest>;

export const PartialInfoRequest = Info.partial();
export type PartialInfoRequest = z.infer<typeof PartialInfoRequest>;
